version: '3.8'

services:

  mongodb:
    image: mongo:6.0

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: tbcare-api-gateway
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - JWT_SECRET=${JWT_SECRET}
      - USER_SERVICE_URL=http://user-service:3001
      - REMINDER_SERVICE_URL=http://reminder-medicine-service:3003
    depends_on:
      - user-service
      - reminder-medicine-service
    networks:
      - tbcare-network
    volumes:
      - ./api-gateway/src:/app/src
    command: npm run dev


  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: tbcare-user-service
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=development
      - MONGO_URI=mongodb://host.docker.internal:27017/tbcare
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=7d
    depends_on:
      - mongodb
    networks:
      - tbcare-network
    volumes:
      - ./user-service/src:/app/src
    command: npm run dev

  reminder-medicine-service:
    build:
      context: ./reminder-medicine-service
      dockerfile: Dockerfile
    container_name: tbcare-reminder-service
    restart: unless-stopped
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - NODE_ENV=development
      - MONGO_URI=mongodb://host.docker.internal:27017/tbcare
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
    networks:
      - tbcare-network
    volumes:
      - ./reminder-medicine-service/src:/app/src
    command: npm run dev

  education-service:
    build:
      context: ./education-service
      dockerfile: Dockerfile
    container_name: tbcare-education-service
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - NODE_ENV=development
      - MONGO_URI=mongodb://host.docker.internal:27017/tbcare
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - tbcare-network
    volumes:
      - ./education-service/src:/app/src
      - ./education-service/uploads:/app/uploads    # ← penting! video tidak hilang saat restart
    command: npm run dev

  skrining-service:
    build:
      context: ./skrining-service
      dockerfile: Dockerfile
    container_name: tbcare-skrining-service
    restart: unless-stopped
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - NODE_ENV=development
      - MONGO_URI=mongodb://host.docker.internal:27017/tbcare
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
    networks:
      - tbcare-network
    volumes:
      - ./skrining-service/src:/app/src
    command: npm run dev

networks:
  tbcare-network:
    driver: bridge

volumes:
  mongodb_data: